AWSTemplateFormatVersion: 2010-09-09
Description: Template to deploy the centralised logging but service catalog product

Parameters:

  Environment:
    Type: String
    Description: The environemnt this template is being deployed into.
    Default: dev

Resources:
  CentralisedLoggingBucket:
    Type: 'AWS::ServiceCatalog::CloudFormationProvisionedProduct'
    Properties: 
      ProvisionedProductName: sccpp-central-logging-bucket #TODO documentation on prefixing the ProvisionedProductName with sccpp- so that the securepipeline deployment roles can deploy
      ProductId: prod-uqstrdr2u5xoc
      ProvisioningArtifactId: pa-77ozkpacjvmwe
      PathName: Storage
      ProvisioningParameters:
        - Key: S3BucketName
          Value: !Sub '${AWS::AccountId}-centralised-logging-bucket'
        - Key: DeletionPolicy
          Value: Delete
        - Key: UpdateReplacePolicy
          Value: Delete
        - Key: Environment
          Value: !Ref Environment
        - Key: Mode
          Value: GOVERNANCE
        - Key: System
          Value: Central-SRE-centralised-logging

      
