AWSTemplateFormatVersion: 2010-09-09
Description: Template to deploy S3 bucket for devplatform template conformance.

Parameters:
  Product:
    Type: String
    Default: GOV.UK
    Description: "Tag all your resources with the product name."

  System:
    Type: String
    Default: dev-platform-conformance
    Description: "Tag all your resources with the service name."

  Owner:
    Type: String
    Default: Central SRE
    Description: "Tag all your resources with the owner name."

  Environment:
    Type: String
    Default: dev
    Description: "The name of the environment you are deploying into and the value for the tag environment to be added to all your resources."
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for encrypting the devplatform template conformance S3 bucket.
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
      Tags:
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
        - Key: Product
          Value: !Ref Product
        - Key: System
          Value: !Ref System
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Source
          Value: "govuk-one-login/central-sre-infra/cloudformation/conformance-s3.yaml"
  
  KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/devplatform-conformance-${AWS::AccountId}-kms-key"
      TargetKeyId: !Ref KMSKey

  S3Bucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "devplatform-conformance-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "aws:kms"
              KMSMasterKeyID: !Ref KMSKey
            BucketKeyEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: GOVERNANCE
            Days: 30
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls: 
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      LifecycleConfiguration:
        Rules:
          - Id: BucketExpiry
            Status: Enabled
            ExpirationInDays: 30
      LoggingConfiguration:
        DestinationBucketName: !Sub "${AWS::AccountId}-centralised-logging-bucket"
        LogFilePrefix: devplatform-conformance
      Tags:
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
        - Key: Product
          Value: !Ref Product
        - Key: System
          Value: !Ref System
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Source
          Value: "govuk-one-login/central-sre-infra/cloudformation/conformance-s3.yaml"
