variable "product_id" {}
variable "artifact_version" {}
variable "object_lock_mode" {}
variable "log_retention_in_days" {}
variable "deletion_policy" {}
variable "update_replace_policy" {}
variable "product" {}
variable "system" {}
variable "environment" {}
variable "owner" {}
